# fly.toml app configuration file generated for life-tracker-backend on 2025-06-17T10:57:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'life-tracker-backend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "life_tracker_data"
  destination = "/app/server/data"
